id: P000517
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 2021-12-16 15:44:07.073154
source_metadata:
  id: bdr:W18135
  title: བསྟན་རྩིས་རེའུ་མིག
  author: ''
  volumes:
    ed35f7b881f74d58abc3cc7d9f0d85fa:
      image_group_id: I5671
      title: ''
      volume_number: 1
      total_pages: 410
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
